### ISSUE TITLE
useAuthState inconsistent persistence

### ISSUE THREAD

**Issue by rohan-deshpande** [CSFrequency/react-firebase-hooks#108] opened 2021-02-13 05:21 UTC
I'm not too sure what is going on but I have two components in my app that use the `useAuthState` hook. 

```js
const  = ({ calloutText }) => {
  const [user, loading] = useAuthState(firebase.auth());

  console.log('WelcomeOrCallout', user);

  if (user) {
    return (
      <span className="button" style={{ display: 'inline-block' }}>
        👋 Welcome back
      </span>
    );
  }

  if (loading) {
    return <Spinner />;
  }

  return <Callout text={calloutText} href={'signup'} />;
};
```

and 

```js 
export const Links = ({ routes }) => {
  const [user, loading] = useAuthState(firebase.auth());

  console.log('Links', user);

  if (loading) {
    return null;
  }

  if (user) {
    return <UserMenu user={user} />;
  }

  return routes.map(
    ({ path, name, url, shouldHideFromNav, requiresAuth }, i) => {
      if (shouldHideFromNav) {
        return null;
      }

      if (requiresAuth && !user) {
        return null;
      }

      return (
        <>
          <li key={i}>
            <NavLink href={path} name={name} url={url} />
          </li>
          <li className="has-button">
            <Callout className="small" text={'Sign up'} />
          </li>
        </>
      );
    }
  );
};
```

Now, here is the weird thing, when I use `useAuthState` in `WelcomeOrCallout`, even after signing out, `Links` returns a user from the hook while `WelcomeOrCallout` does not. 

If I do NOT use `useAuthState` in `WelcomeOrCallout`, `Links` works as expected, not rendering the `UserMenu`. 

Is there anything I am doing wrong here that could cause this to happen? Scratching my head honestly. 

Here's my sign out page code (this is a next-js app)

```js
export default () => {
  firebase.auth().signOut();

  return (
    <Page>
      <Content loading />
      <Redirect route="/" />
    </Page>
  );
};
```

**Note:** What's also interesting is that if I log `firebase.auth()` in both components, after signing out the `currentUser` value is `null`. So it seems that the sign out is working on the firebase client end, but the hook isn't updating correctly?

**Comment by rohan-deshpande** [comment] 2021-02-13 05:43
Okay so, seems like the issue was caused by having a dedicated `logout` page and performing the sign out there. I've changed my code to simply do this when a user clicks the Logout button

```js
                onClick={async () => {
                  await firebase.auth().signOut();
                  Router.push('/');
                }}
```

And everything is working. I'll leave this open as I feel the above issue is still kind of interesting and I'd like to know why it's not working as expected.

**Comment by dohomi** [comment] 2021-03-24 04:49
@rohan-deshpande your logout page code does not seem right to begin with. You should keep the signOut inside of useEffect:
```js
export default () => {
  const { push } = useRouter()
  useEffect(() => {
    const logout = async () => {
        await firebase.auth().signOut()
        await push('/')
    }
    logout()
  }, [push])
  return 'logging out...'
}
```

**Comment by warent** [comment] 2021-03-27 00:35
I'm having this same problem with `useSignInWithEmailAndPassword`

My usecase is for the root App to use that hook to verify auth. If the user is authenticated, the App component returns the router with all the routes and pages. If they're not authenticated, it just returns an Auth component.

The Auth component uses useSignInWithEmailAndPassword therein. When `signInWithEmailAndPassword` is fired, the `useSignInWithEmailAndPassword` hook within the Auth component updates its state with the new user, etc. But the parent App component with the same hook has no update from the hook.

I'm guessing there's a bug in how the event listeners are implemented. Probably the best way to resolve this is to wrap it in a context, but then I don't see the point of these hooks and may as well just access the firebase SDK directly

**Comment by dohomi** [comment] 2021-03-27 01:39
@warent I think its quite a legit use case to use a provider on top of your app tree with `useAuthState` and pass the user object down the page tree as a context.

**Comment by warent** [comment] 2021-03-27 01:41
Sure, it is a legitimate pattern. That still does not address that multiple hooks is breaking. My goal here is to report a bug + add info / context, not seek workarounds.

**Comment by dohomi** [comment] 2021-03-27 01:58
@warent do you have a repo to look at? @rohan-deshpande fixed his issue with having a wrong implementation on the sign-out process. I think it make sense and maybe should be mentioned by the author of this repo that the `useAuthState` should be used on the top level of the app and the value be passed down via context or props. Not sure if thats 100% correct just trying to help. I just started to use firebase few weeks ago for a client project and with a provider the user state worked fine for me.

**Comment by nickroberts** [comment] 2021-04-14 14:29
I see the same issue when calling `user.updateProfile({ displayName, photoURL });`.

I was assuming the `user` from `userAuthState(auth);` would get updated when we update the profile.

I am using the `useAuthState(auth)` hook in multiple applications, but it doesn't seem like they are actually subscribing to updates.

I'd rather not create a provider, or pass the user down from the app, if at all possible.

**Comment by lorstenoplo** [comment] 2021-04-14 14:54
@nickroberts I guess the useAuthState hook itself isn't programmed to listen for updates in user profile. Have experienced the issue while the user has logged out? Is the hook showing the updates in this case?

**Comment by nickroberts** [comment] 2021-04-14 16:41
The hook fires when logging out, so it does trigger. I guess I'll have to figure out a way to handle updating the user profile. It's not a deal breaker, but it's just a bit odd. 😄

**Comment by lorstenoplo** [comment] 2021-04-15 02:35
@nickroberts Maybe I'll check the docs and create a pr but if you've got time please try making a pr and if u are into it just inform me.

**Comment by chrisbianca** [comment] 2021-04-24 07:15
@nickroberts this is a limitation of the underlying `onAuthStateChanged` method as described here: https://firebase.google.com/docs/reference/js/firebase.auth.Auth#onauthstatechanged

The underlying method only fires on login and logout, not when the user changes. Unfortunately there are no other listeners built into the Firebase library that would allow this to work any better. 

To achieve the result you're hoping for would require a completely different approach including the addition of a hook for every Firebase method that makes changes to the user object. It's certainly possible, but not something that I have the time for at the moment, however am very open to contributions to the library. I am going to close this issue and raise a feature request instead.

**Closed by chrisbianca** 2021-04-24 07:15 UTC

**Comment by chrisbianca** [comment] 2021-04-24 07:23
See https://github.com/CSFrequency/react-firebase-hooks/issues/147

**Comment by warent** [comment] 2021-04-24 08:32
The original bug reported here is unrelated to #147 or user updates. The problem is that useAuthState doesnt work if used in multiple places.

**Comment by klutchdev** [comment] 2021-07-09 16:45
are y'all still having an issue?? I have a fairly large sized ecommerce app that uses this in multiple components, along with it's back office counterpart that uses it at the top level with context. Both apps operate properly without any notable difference and update in real time when auth is updated
