### ISSUE TITLE
[Firerstore] useCollection - useCollectionOnce timestamp filter

### ISSUE THREAD

**Issue by mfanselmo** [CSFrequency/react-firebase-hooks#72] opened 2020-06-25 03:38 UTC
When using useCollection with a query that uses a timestamp, react goes into a recursive state.

```js
const now = firebase.firestore.Timestamp.now();
const [allApplications, loadingApplications, errorLoading] = useCollection(
     firebase.db.collection(...).where('endDate', '>', now)
 );
```
The hook is not in a useEffect or anything like that.
This happens 
![image](https://user-images.githubusercontent.com/26393563/85650437-8f4e7780-b673-11ea-86c6-ed0cef3c824c.png)

For context, this works with no problems
```js
  useEffect(() => {
    const unsubscribe = firebase.sameQuery
      .onSnapshot((snapshot) => {
        if (snapshot.size) {
          // we have something
          setAllApplications(snapshot);
          setLoadingA(false);
        } else {
          // it's empty
          console.log('empty');
          setLoadingA(false);
        }
      });
    return () => {
      unsubscribe();
    };
  }, [firebase.applicationLogic]);

```

**Comment by afreeland** [comment] 2020-08-31 04:15
Was there any updates on what causes this behavior...or is it an incorrect way to call the hook. Seen this issue and was curious if there was any solution/alternative?

**Comment by nmaves** [comment] 2020-08-31 14:39
This is not the correct way to use this or any hook.  The issue is that `now` will have a new value on every render.  Wrap that in a useMemo.

```
const now = React.useMemo(() => firebase.firestore.Timestamp.now(), [])
const [allApplications, loadingApplications, errorLoading] = useCollection(
     firebase.db.collection(...).where('endDate', '>', now)
 );
```

**Comment by chrisbianca** [comment] 2020-12-30 07:20
Closing this as it's not an issue with the library

**Closed by chrisbianca** 2020-12-30 07:20 UTC
