### ISSUE TITLE
initialising and error not working on Auth Hook

### ISSUE THREAD

**Issue by HausOfAlejandro** [CSFrequency/react-firebase-hooks#29] opened 2019-07-13 02:24 UTC
Hello there! :-)

I'm using the same code provided as example and the **initialising** and **error** states are never reached... login and logout are working fine.

Just found a [related topic](https://github.com/CSFrequency/react-firebase-hooks/issues/1), but I installed the "react-firebase-hooks" packpage today so it shouldn't be happening.

**Comment by chrisbianca** [comment] 2019-08-02 07:12
@HausOfAlejandro can you check your `package-lock.json` or `yarn.lock` to see what version of `react-firebase-hooks` has been installed?

**Comment by HausOfAlejandro** [comment] 2019-08-02 13:30
> @HausOfAlejandro can you check your `package-lock.json` or `yarn.lock` to see what version of `react-firebase-hooks` has been installed?

Hi! is ^2.0.0

**Comment by chrisbianca** [comment] 2020-05-25 07:19
Closing as I cannot reproduce

**Closed by chrisbianca** 2020-05-25 07:19 UTC

**Comment by ynnoj** [comment] 2020-06-14 08:59
@chrisbianca This is a widely reported issue facing multiple users (#43, #46).

Using the example in the `useAuthState` README is a clear reproduction. Please can you investigate this further.

**Comment by slk333** [comment] 2020-09-26 01:03
@ynnoj did you find a solution?
Ran into the exact same issue.
Can't believe fireship.io actually recommended this package

**Comment by ynnoj** [comment] 2020-09-26 11:43
> @ynnoj did you find a solution?
> 
> Ran into the exact same issue.
> 
> Can't believe fireship.io actually recommended this package

Nope. Just using the Firebase SDK directly.

**Comment by pvhieuit** [comment] 2020-10-21 05:34
Same issue

**Comment by lorstenoplo** [comment] 2021-01-05 15:28
@chrisbianca I have fixed this issue in PR : #98 , please check if it can be merged
