### ISSUE TITLE
How to handle Errors from Firestore

### ISSUE THREAD

**Issue by sven09** [CSFrequency/react-firebase-hooks#25] opened 2019-06-11 23:44 UTC
Hi,
I'm using 
```
const query = firestore.collection('cms').doc('events').collection('cmsevents');
		const options =
		{
			idField: '_uid'
		}
		try {
			const [values, loading, fberror] = useCollectionDataOnce<IEvent>(query, options);
			console.log('values, loading, fberror', values, loading, fberror)

			// Production code
			return (
				<div>
					<Title>Your Events</Title>
					{error ? (
						<Alert variant="danger" onClose={() => setError(null)} dismissible>
							<Alert.Heading>Error</Alert.Heading>
							<p>{error}</p>
						</Alert>
					) : null}

					{fberror && <strong>Error: {fberror}</strong>}
					{loading && <span>Document: Loading...</span>}
					{values && <pre>Documents: {JSON.stringify(values, null, 2)}</pre>}

					<Button onClick={() => {
						history.push('events/_new');
					}
					}>Add</Button>


				</div>
			);
		} catch (error) {
			return (<pre>{JSON.stringify(error, null, 2)}</pre>)
		}
```
 It works perfect.

But if i update my roles in firestore, i will get a exception
`
FirebaseError: Missing or insufficient permissions. 
`

Getting this error is ok. 
My expectation was, that this is also caught and add to error.
Unfortunately this is not the case and my side crashes.

Do you have any suggestions how to catch the firestore exception?

Many thanks!

**Comment by chrisbianca** [comment] 2019-08-02 07:49
@sven09 Sorry for the delayed response on this.  I'm struggling to reproduce this issue:

1) I've set my firestore rules to only allow reading data if the user is authenticated
2) I've logged the user out
3) I've attempted to read data from Firestore
4) The error is being correctly caught and comes through in the `error` property from `useCollectionDataOnce`

```
Collection Data Error: {"code":"permission-denied","name":"FirebaseError"}
```

What version of `react-firebase-hooks` and `firebase` are you using in your project?

**Comment by chrisbianca** [comment] 2020-05-25 07:18
Closing due to lack of follow up

**Closed by chrisbianca** 2020-05-25 07:18 UTC
