### ISSUE TITLE
loading is false when ref if changed.

### ISSUE THREAD

**Issue by hlehmann** [CSFrequency/react-firebase-hooks#21] opened 2019-05-26 12:55 UTC
Version: 2.0.0

After changing the ref in useDocumentData I first get loading: false, value: undefined.
It seems that the isEqualRef is called afterward.

When the ref change, loading should immediately set to true.

**Comment by chrisbianca** [comment] 2019-05-29 14:38
@hlehmann this looks like a duplicate of https://github.com/CSFrequency/react-firebase-hooks/issues/17 caused by the way that the hooks run in sequence.  I'm still looking into whether a workaround is possible or not, so please follow #17 for updates.

**Closed by chrisbianca** 2019-05-29 14:38 UTC

**Comment by hlehmann** [comment] 2019-06-12 10:47
Could this 
```typescript
export const useComparatorRef = <T>(
  value: T | null | undefined,
  isEqual: (v1: T | null | undefined, v2: T | null | undefined) => boolean,
  onChange?: () => void
): RefHook<T | null | undefined> => {
  const ref = useRef(value);
  useEffect(() => {
    if (!isEqual(value, ref.current)) {
      ref.current = value;
      if (onChange) {
        onChange();
      }
    }
  });
  return ref;
};
```
be
```typescript
export const useComparatorRef = <T>(
  value: T | null | undefined,
  isEqual: (v1: T | null | undefined, v2: T | null | undefined) => boolean,
  onChange?: () => void
): RefHook<T | null | undefined> => {
  const ref = useRef(value);
  const initRef = useRef(true);
  if (!isEqual(value, ref.current)) {
    ref.current = value;
  }
  useEffect(() => {
    if (initRef.current) {
      initRef.current = false
    } else if (onChange) {
      onChange();
    }
  }, [ref.current]);
  return ref;
};
```

https://github.com/CSFrequency/react-firebase-hooks/blob/master/util/refHooks.ts#L14
