### ISSUE TITLE
useDocumentData returns undefined on first render until forced browser refresh returns data

### ISSUE THREAD

**Issue by BinDohry** [CSFrequency/react-firebase-hooks#252] opened 2022-07-01 07:16 UTC
```js
import { doc } from 'firebase/firestore';
import { createContext, useEffect, useState } from 'react';
import { auth, db } from '../firebase/firebase-config';
import {
  useDocumentData,
  useDocumentDataOnce,
} from 'react-firebase-hooks/firestore';
import { useAuthState } from 'react-firebase-hooks/auth';

const userAuthContext = createContext({});

const UserAuthContextProvider = ({ children }: any) => {

  const [authUser, loadingAuthUser, errorAuthUser] = useAuthState(auth);
  
  const [authUserDocRef, setAuthUserDocRef]: any = useState();
  
  const [userData, loading, error, snapshot, reload] =
    useDocumentDataOnce(authUserDocRef);

  const [businessDocRef, setBusinessDocRef]: any = useState();

  const [
    businessData,
    loadingBusinessData,
    errorBusinessData,
    snapshotBusinessData,
  ] = useDocumentData(businessDocRef);

  useEffect(() => {
    if (authUser) {
      setAuthUserDocRef(doc(db, 'users', authUser.uid));
    }

    if (userData) {
      setBusinessDocRef(userData.managedBusiness);
    }
  }, [authUser, userData]);

  return (
    <userAuthContext.Provider
      value={{ authUser, businessData, loadingBusinessData }}
    >
      {children}
    </userAuthContext.Provider>
  );
};

export { userAuthContext, UserAuthContextProvider };
```
businessData returns undefined. I have to manually force refresh the browser for businessData to return the correct value from Firestore.

**Comment by pythonicode** [comment] 2022-07-02 02:15
Same issue here. not sure why this is happening.

**Comment by Yey007** [comment] 2022-07-12 08:33
I'm facing a very similar issue with useDocumentDataOnce. It won't load, always returning undefined and true for the loading value until I make a change in the code and the module reloads. Very bizarre.

**Comment by Yey007** [comment] 2022-07-12 08:47
I'm glad you fixed your issue. Here is my minimal reproducible example. The document is stuck in the loading state forever.

```ts
const Test: React.FC = () => {
  const { id } = useParams<{ id: string }>();

  const db = getFirestore();
  const docRef = doc(collection(db, 'classes'), id);

  const [course, courseLoading, courseError] = useDocumentDataOnce(docRef);

  if (courseLoading) {
    console.log('loading');
    return <LoadingPage></LoadingPage>;
  }

  if (courseError) {
    console.log('error');
    return <ErrorPage></ErrorPage>;
  }

  console.log(':)');
  return <div>:)</div>;
};
```
"loading" is logged, and then nothing. Perpetual loading. The id is a valid id and the reference exists. I know because everything loads fine after I reload the module by making a change. Even more bizarre is the fact that we don't face this issue in the live production build.

**Comment by Yey007** [comment] 2022-07-12 13:58
@BinDohry It's the same deal, unfortunately.

**Comment by marduzca** [comment] 2022-07-15 09:14
@BinDohry 
Interesting, that I didn't expect. Not sure what the problem is then

**Comment by Garee** [comment] 2022-08-06 07:47
I am also encountering this issue using React v18. I've switched from `useDocumentDataOnce` to `useDocumentData` as a temporary workaround.

**Comment by Yey007** [comment] 2022-08-23 15:06
@Garee Yeah, that's the workaround I found as well. I'm not exactly sure why this is happening, but I unfortunately don't have the time to investigate. I wish I could.

**Comment by lewisd1996** [comment] 2022-09-09 21:41
Currently suffering the same problem

**Comment by lewisd1996** [comment] 2022-09-09 22:23
I have now fixed this. I had to delete `node_modules` as well as my `.next` folder and reinstall

**Comment by jamesdarabi** [comment] 2022-09-12 06:41
I'm also having the same issue. As mentioned above, using `useDocumentData` works as a temporary workaround.

Here are my relevant dependencies:

```json
  "firebase": "^9.9.4",
  "next": "12.3.0",
  "react": "18.2.0",
  "react-dom": "18.2.0",
  "react-firebase-hooks": "^5.0.3",
```

**Comment by Yey007** [comment] 2022-09-17 02:33
@lewisd1996 in the same situation. Unfortunately reinstalling did not work for me. Tried deleting the lock file and node modules to no avail.

**Comment by jdgamble555** [comment] 2022-09-23 13:47
It is returning `undefined` here 

https://github.com/CSFrequency/react-firebase-hooks/blob/master/firestore/useDocument.ts#L98

and same thing with collections

https://github.com/CSFrequency/react-firebase-hooks/blob/master/firestore/useCollection.ts#L80

Someone needs to debug this perhaps and submit a pull request.

J

**Comment by chrisbianca** [comment] 2022-11-09 16:55
Hi everybody, apologies for the delay in investigating this properly. I've just given this a try and it appears that some of the changes I've made in the newly released v5.1.0 may have inadvertently resolved this issue.

Could I ask you to try v5.1.0 and check whether this has been fixed?

**Comment by pythonicode** [comment] 2022-11-10 06:40
Tested again and it seems to work fine. Thanks for the update!

**Comment by chrisbianca** [comment] 2022-11-10 16:22
Thanks @pythonicode, I will close this issue, but if anybody else is still struggling, please let me know and I can look into it further!

**Closed as completed by chrisbianca** 2022-11-10 16:22 UTC
Labels: feedback wanted

**Comment by utkudotdev** [comment] 2022-12-04 03:11
@chrisbianca Thank you so much, the fix works!
